### ISSUE TITLE
Bad connection?

### ISSUE THREAD

**Issue by fredrikr** [daelsepara/heart-of-ice#1]
At the beginning, when I've accepted to travel with the other person and we reach a mountain pass where we see some dead people and I choose to investigate closer, I'm thrown to passage 265 which seems to be a mistake. Text talks about a scribe, about laptops and a modem, all of which are new to me.

**Comment by daelsepara** [comment]
I'll review connections. I may have missed a few. Thanks for reporting.

**Comment by daelsepara** [comment]
Should be fixed in the latest story file: https://github.com/daelsepara/heart-of-ice/releases/latest/download/heartice.z5
