### ISSUE TITLE
Endless CPU spin because of input polling

### ISSUE THREAD

**Issue by reallew** [daelsepara/heart-of-ice#2]
Thanks for this game!

But it burns a lot of electricity because it uses 100% of one CPU core for a busy wait for inputs. This makes it not playable on my laptop running on battery. Please fix this by replacing the calls `SDL_PollEvent(&result);` with `SDL_WaitEvent(&result);` in the file input.hpp, that should fix it.

**Comment by daelsepara** [comment]
Hi. Thanks for the fix. I have made the corresponding changes. At the moment, I can only update the source code and the .deb packages.
